platform: linux

inputs:
  - name: source-ci
  - name: certification
  - name: director-config
  - name: bosh-release
  - name: cpi-release
  - name: stemcell
  - name: environment

outputs:
  - name: director-state

run:
  path: source-ci/ci/tasks/deploy-director.sh
