platform: linux
image_resource:
  { type: docker-image, source: { repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/vsphere-vcpi } }
inputs:
  - name: source-ci
  - name: environment
outputs:
  - name: dummy # dummy output to avoid sending the entire task over the network
run:
  path: source-ci/ci/tasks/extend-lease.sh
