platform: linux
image_resource:
  { type: registry-image, source: { repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/vsphere-vcpi } }

inputs:
- name: source-ci
- name: bosh-cpi-src
- name: bosh-cpi-artifacts
- name: release-version-semver

run:
  path: source-ci/ci/tasks/inspect-candidate.sh
