platform: linux
image_resource:
  { type: docker-image, source: { repository: gcr.io/cf-pas-nx-t-pineapple/vcpi-main } }

inputs:
  - name: source-ci
  - name: certification
  - name: environment
  - name: bosh-deployment
  - name: bosh-release
  - name: cpi-release
  - name: stemcell

outputs:
  - name: director-config

run:
  path: source-ci/ci/tasks/prepare-director.sh
