---
platform: linux

inputs:
  - name: source-ci
  - name: bosh-cpi-src
  - name: bosh-cpi-artifacts
  - name: release-version-semver

outputs:
  - name: updated-repo
  - name: final-release-tag

run:
  path: source-ci/ci/tasks/promote-candidate.sh

params:
  AWS_ACCESS_KEY_ID:     ""
  AWS_SECRET_ACCESS_KEY: ""
  AWS_ASSUME_ROLE_ARN: ""
