platform: linux

inputs:
  - name: source-ci
  - name: certification
  - name: environment
  - name: bats
  - name: director-state
  - name: bosh-cli
  - name: stemcell

run:
  path: source-ci/ci/tasks/run-bats-cvds.sh

params:
  STEMCELL_NAME:      ""
  BAT_RSPEC_FLAGS:    ""
