platform: linux
image_resource:
  { type: docker-image, source: { repository: gcr.io/cf-pas-nx-t-pineapple/vcpi-main } }

inputs:
  - name: source-ci
  - name: certification
  - name: director-state
  - name: environment

run:
  path: source-ci/ci/tasks/teardown.sh
