platform: linux
image_resource:
  { type: docker-image, source: { repository: gcr.io/round-essence-187720/python, tag: '2.7' } }
inputs:
  - name: source-ci
  - name: bosh-cpi-src
run:
  path: source-ci/ci/tasks/test-pyvmomi_to_ruby.sh
