platform: linux
image_resource:
  { type: docker-image, source: { repository: gcr.io/cf-pas-nx-t-pineapple/vcpi-main } }
inputs:
- name: source-ci
- name: bosh-cpi-src
run:
  path: source-ci/ci/tasks/unit-test.sh
