platform: linux
image_resource:
  { type: registry-image, source: { repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/vsphere-vcpi } }
inputs:
- name: source-ci
- name: bosh-cpi-src
run:
  path: source-ci/ci/tasks/unit-test.sh
