platform: linux
image_resource:
  { type: registry-image, source: { repository: harbor-repo.vmware.com/dockerhub-proxy-cache/bosh/vsphere-vcpi } }

inputs:
  - name: certification
  - name: bosh-cli
  - name: bosh-deployment
  - name: environment
  - name: director-state
  - name: source-ci

params:
  OPTIONAL_OPS_FILE:  ""

run:
  path: source-ci/ci/tasks/update-cloud-config.sh
