jobs:
- name: build-vcpi-main-image
  plan:
  - get: source-ci
  - get: source-ci-trigger
    trigger: true
  - get: ubuntu-base-image
    trigger: true
  - config:
      image_resource:
        name: ""
        source:
          repository: harbor-repo.vmware.com/dockerhub-proxy-cache/vito/oci-build-task
        type: registry-image
      inputs:
      - name: source-ci
      outputs:
      - name: image
      params:
        CONTEXT: source-ci/ci/docker
      platform: linux
      run:
        path: build
    privileged: true
    task: build
  - params:
      image: image/image.tar
    put: vcpi-main-image
resources:
- name: source-ci
  source:
    branch: master
    paths:
    - ci
    private_key: ((github_deploy_key_bosh-vsphere-cpi-release.private_key))
    uri: git@github.com:cloudfoundry/bosh-vsphere-cpi-release.git
  type: git
- name: source-ci-trigger
  source:
    branch: master
    paths:
    - ci/docker
    private_key: ((github_deploy_key_bosh-vsphere-cpi-release.private_key))
    uri: git@github.com:cloudfoundry/bosh-vsphere-cpi-release.git
  type: git
  check_every: 1h
- name: ubuntu-base-image
  source:
    repository: harbor-repo.vmware.com/dockerhub-proxy-cache/library/ubuntu
    tag: 18.04
  type: registry-image
  check_every: 1h
- name: vcpi-main-image
  source:
    repository: bosh/vsphere-vcpi
    tag: latest
    username: ((docker.username))
    password: ((docker.password))
  type: registry-image
  check_every: never

