# fly -t bosh-vsphere sp -p docker-image-build -c ci/pipeline/docker-image-build.yml
jobs:
- name: build-vcpi-main-image
  plan:
  - get: source-ci
    tags: [nimbus]
  - get: source-ci-trigger
    tags: [nimbus]
    trigger: true
  - get: bosh-golang-release-image
    tags: [nimbus]
    trigger: true
  - task: build
    tags: [nimbus]
    config:
      image_resource:
        source:
          repository: harbor-repo.vmware.com/dockerhub-proxy-cache/concourse/oci-build-task
        type: registry-image
      inputs:
      - name: source-ci
      outputs:
      - name: image
      params:
        CONTEXT: source-ci/
        DOCKERFILE: source-ci/ci/docker/Dockerfile
        IMAGE_PLATFORM: linux/arm64,linux/amd64
        OUTPUT_OCI: true
      platform: linux
      run:
        path: build
    privileged: true
  - put: vcpi-main-image
    tags: [nimbus]
    params:
      image: image/image
resources:
- name: source-ci
  tags: [nimbus]
  source:
    branch: master
    paths:
    - ci
    private_key: ((github_deploy_key_bosh-vsphere-cpi-release.private_key))
    uri: git@github.com:cloudfoundry/bosh-vsphere-cpi-release.git
  type: git
- name: source-ci-trigger
  tags: [nimbus]
  source:
    branch: master
    paths:
    - ci/docker
    private_key: ((github_deploy_key_bosh-vsphere-cpi-release.private_key))
    uri: git@github.com:cloudfoundry/bosh-vsphere-cpi-release.git
  type: git
  check_every: 1h
- name: vcpi-main-image
  tags: [nimbus]
  source:
    repository: bosh/vsphere-vcpi
    tag: latest
    username: ((docker.username))
    password: ((docker.password))
  type: registry-image
  check_every: never
- name: bosh-golang-release-image
  tags: [nimbus]
  type: registry-image
  source:
    repository: bosh/golang-release
    username: ((docker.username))
    password: ((docker.password))
