---
resources:
  - name: every-day
    type: time
    icon: clock-outline
    source:
      start: "1:00 AM"
      stop:  "4:00 AM"
      location: America/Los_Angeles
      interval: 24h

jobs:
  - name: cleanup
    public: true
    plan:
      - get: every-day
        trigger: true
      - task: cleanup
        params:
          DATACENTER: wdc
          USER: svc.tas-anycloud
          NIMBUS_LOCATION: wdc
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: devtools-docker-local.artifactory.eng.vmware.com/vmware/nimbus/nimbus-worker }
          run:
            path: /bin/bash
            args:
              - -ec
              - |
                TESTBED_FILE=/tmp/testbed.$$.txt
                nimbus-ctl --testbed list > $TESTBED_FILE
                sort -k 2 < $TESTBED_FILE | # sort by testbed name
                  grep -v "^ " | # remove the VMs, keep only the testbed info
                  grep -v "svc.tas" | # don't kill the MaaS testbeds
                  grep -v "\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\.\." | # remove status dots
                  grep -v "=================" | # remove separator
                  grep -v "lease expires at unknown" | # ignore zombie testbeds which have no VMs
                  cut -b 16-512 | # remove weird & useless datacenter info
                  sed 's=(ID: .......),.*==' | # remove everything but the testbed name
                  awk '
                BEGIN { OLD_TESTBED=""; OLD_TESTBED_TIMESTAMP="" }
                {
                  CURRENT_TESTBED=gensub(/-[0-9]+$/, "", "")
                  CURRENT_TESTBED_TIMESTAMP = gensub(/.*-([0-9]+)$/, "\\1", "")
                  if ( OLD_TESTBED != "" ) {
                     if ( OLD_TESTBED != CURRENT_TESTBED ) {
                        print "# skipping " OLD_TESTBED "-" OLD_TESTBED_TIMESTAMP " because it is the most recent"
                     } else {
                        print "nimbus-ctl --testbed kill " OLD_TESTBED "-" OLD_TESTBED_TIMESTAMP
                        system("nimbus-ctl --testbed kill " OLD_TESTBED "-" OLD_TESTBED_TIMESTAMP)
                     }
                  }
                  OLD_TESTBED = CURRENT_TESTBED
                  OLD_TESTBED_TIMESTAMP = CURRENT_TESTBED_TIMESTAMP
                }
                END { print "# skipping " OLD_TESTBED "-" OLD_TESTBED_TIMESTAMP " because it is the most recent" }
                '
